language: python
dist: trusty
python:
- 3.5.1
install:
- pip install -r requirements.txt
script:
- python ./setup.py install
- py.test --cov ttqpy test
deploy:
  provider: heroku
  api_key:
    secure: p28+Qqlo27K0rqJZcaKArsTDSqLmdW6DxYI5+3PpE0wV+NjRv0kYZF0JdH4vxMUj1VDfSygi68OCd/64o3y4wPii1yqvN7lGX1Sz3kJ1S1IKxWcN8kR3Fk4uEN4K3FRMXgDxouYHR3NM2ZiRUGnvfWw2gYsdSZ8/Oe/sYkirhD9i1UmhFAGOvHY6b2kOAg0bFanNla6fcvijM0Sl05XC8PM1odZSZwgZIrpuSmVwLoOkIMNv+RmQxbOWsu5ft9WPLeTKpYFWV7bcFPC3uQ8HNeBkedKwzLILTOU2HUXqwa8Bzko2EhCr5dQz5FATQAKJ8EevqbIRGDkdg1M2IefJJhijxMMBUBB5ZRnObZBWrSGhNHPCQHEPbGi9yffVs4kjBLx1lzNLCk/y+tcNoWYgc3awqoWWIBqYIlDpzAoBPkKM89UfO/SEfcAaw6br1iZ0cpD878lxRnRU/bmprTqmIcot5nWiB9wEuvnh67t05O1/VfMcmNhGAoKQipA7C1VXNHEZdsLYqE2hTRI+/V5alQ/tNv5KsCK6KCBMtuLJY5brrIqy6/9Z9/Z6a615gqcmgtfSionX5i8n1bT6+VZoLmQybOKll3icgKCpU0URv/zfIQjWnzxLu5u67KuSGxvC1VOI5j4OBp/PCsLCQU2Oi2CcIwQDBswwHFgzjNOoHLE=
  app: ttqpy
  on:
    repo: zachdicus/ttqpy
