language: python
dist: trusty
python:
- 3.5.1
install:
- pip install -r requirements.txt
script:
- python ./setup.py install
- py.test --cov ttqpy test
deploy:
  provider: heroku
  api_key:
    secure: sLD36cVgsg8Vy7zYJbvAoqbuQuZPHWTrPDIn9J6CEKTA5D0D9Dnkn87BeXZICPIA+IsGuhlyThG7tMR59bfHa/I7u5lNVR/w/z6a6tPzBAo5ghNO/s+jOkNXT+2UxefAdtx9bn78YTboYFz3nUtOEz/GdczEL541Ov7y0CkZcCkIPnD5mK/mAexVcl64mhRhwLSLeoySNKoFrTPxlySXy5qmfRNSZxFP1MjYltvoxO7FWF0vS8nmSC4hVsB5VXqE3cOUeFKwPNl9cSKhONbcLOj3AZs0AwuZs7Sg/YqVB2n7KpfL+cym+TAkFHp1R8VmlxuXorWbYGqkAACYB8yqqCfNkghF+qqKQ1Xtxhq07UoSmGDzgoDI9llbnKnwPiyRgqzNYIkj0cFMwh2GwdIGbcO9AYcKDgOHKeAlhL1uSF3iei6su8c/SDu3tamwUcFDnq9PV0sMSiXAiDaPUApEqY7QL5N+3DEHahe1xfgQgjmZL4F65ujzmy+OBRlgUfWkoW828B71Z5RWI05v2huV9ezHvU0S3d3qlEbCsMGESKH3U00uwxOT1Nr/KUjk0Tlg3qkBed0/wP10M40X72Hy2dGGhmFx3GRnZzozMouStWIdg7GxO3FsiJtpT+fpVA8GTZKWs9awybjeCSd7hp1UdRCb7L9atoq4m4QEvX+lrig=
  app: ttqpy
  on:
    repo: zachdicus/ttqpy
